services:
  backend:
    image: todo-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    volumes:
            - ./config:/app-config
            - ./data:/app-data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5200
    depends_on:
            - mysql
    restart: always
    logging:
        driver: json-file
        options:
            max-file: "1"
            max-size: 10m

  adminer:
    image: adminer
    restart: always
    ports:
      - 5300:8080
    depends_on:
          - mysql

  mysql:
    image: mariadb:10.5
    # image: mysql:8.0 # 囲み文字を使用する場合
    volumes:
        - mysql-db:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: todo-backend
        MYSQL_USER: todo-backend
        MYSQL_PASSWORD: todo-backend
        TZ: "Asia/Tokyo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password # for myql
    restart: always
    logging:
        options:
            max-size: "10m"
            max-file: "3"

volumes:
    mysql-db:


